console.log('Superalgos is growing...! and now, besides the platform for algo-traders, there is a p2p Network (under development) and a Social Trading Desktop app (under development).')
console.log('')
console.log('For that reason, the "node run" command was deprecated and now you need to use one of these:')
console.log('')
console.log('node platform --------------- This will run the Platform for algo-tarders.')
console.log('node network  --------------- This will run the p2p Network for social trading.')
console.log('node desktop  --------------- This will run the Desktop App for crypto users willing to engage in social trading.')