console.log('Superalgos is growing! In addition to the Platform for algo-traders, there is a P2P Network (under development) and a Social Trading Desktop App (under development).')
console.log('')
console.log('For that reason, the "node run" command has been deprecated. Please, use one of these instead:')
console.log('')
console.log('node platform --------------- Runs the Superalgos Platform for algo-traders.')
console.log('node network  --------------- Runs the P2P Network for social trading.')
console.log('node desktop  --------------- Runs the Desktop App for crypto users.')
