const GRAPHQL_MUTATION_UPDATE_STRATEGY = Apollo.gql`
    query($fbSlug: String!){

              strategizer_StrategyByFb(fbSlug: $fbSlug){
              subStrategies(activeOnly: true){
                  name
                  entryPoint{
                  situations{
                      name
                      conditions{
                      name
                      code
                      }
                  }
                  }
                  exitPoint{
                  situations{
                      name
                      conditions{
                      name
                      code
                      }
                  }
                  }
                  sellPoint{
                  situations{
                      name
                      conditions{
                      name
                      code
                      }
                  }
                  }
                  buyPoint{
                  situations{
                      name
                      conditions{
                      name
                      code
                      }
                  }
                  }
                  stopLoss{
                  phases{
                      name
                      code
                      situations{
                      name
                      conditions{
                          name
                          code
                      }
                      }
                  }
                  }
                  buyOrder{
                  phases{
                      name
                      code
                      situations{
                      name
                      conditions{
                          name
                          code
                      }
                      }
                  }
                  }
                  sellOrder{
                  phases{
                      name
                      code
                      situations{
                      name
                      conditions{
                          name
                          code
                      }
                      }
                  }
                  }
              }
              }
          }
        `
