function newSuperalgosGlobalsZoom() {
    thisObject = {
        DOUBLE_CLICK_ZOOM_OUT_LEVEL: 0,
        DOUBLE_CLICK_ZOOM_IN_LEVEL: 6,
        DOUBLE_CLICK_ZOOM_IN_IN_LEVEL: 7,
        ZOOM_OUT_THRESHOLD_FOR_NOT_HIDDING_PANELS: 12,
        ZOOM_OUT_THRESHOLD_FOR_HIDDING_PANELS: 7,
        ZOOM_OUT_THRESHOLD_FOR_CHANGING_TIME_FRAME: 3,
        ZOOM_OUT_THRESHOLD_FOR_PACKING_OBJECTS_AT_THE_BOTTOM_OR_TOP_OF_VIEWPORT: 2,
        ZOOM_OUT_THRESHOLD_FOR_PLOTTING_IN_LOW_RESOLUTION: 3,
        ZOOM_OUT_THRESHOLD_FOR_DISPLAYING_TIME_MACHINES_ICONIZED: 5,
        ZOOM_OUT_THRESHOLD_FOR_DISPLAYING_SCALES: 3
    }
    return thisObject
}